name: Bug Report
description: File a bug report to help us improve pi-web
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the documentation and troubleshooting guide
          required: true
        - label: I am running this on a Raspberry Pi or ARM-compatible device
          required: false

  - type: dropdown
    id: raspberry-pi-model
    attributes:
      label: Raspberry Pi Model
      description: Which Raspberry Pi model are you using?
      options:
        - Raspberry Pi 4 Model B
        - Raspberry Pi 3 Model B+
        - Raspberry Pi 3 Model B
        - Raspberry Pi Zero 2 W
        - Other ARM device
        - x86_64 (for testing)
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: Operating System
      description: What OS and version are you running?
      placeholder: "e.g., Raspberry Pi OS 64-bit, Ubuntu 22.04"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run `make install`
        2. Navigate to `http://monitoring.pi.home`
        3. See error...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Please copy and paste any relevant log output
      render: shell
      placeholder: |
        # Service status
        make status
        
        # Service logs
        journalctl -u proxy.service --no-pager -l
        journalctl -u monitoring.service --no-pager -l
        journalctl -u n8n.service --no-pager -l

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Additional environment information
      placeholder: |
        - Docker version: 
        - Docker Compose version:
        - Available memory:
        - SD card type/speed:
        - Network configuration:

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, configuration changes, etc.
