name: Feature Request
description: Suggest an idea for pi-web
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! We appreciate your input to make pi-web better.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: This feature would benefit the broader pi-web community
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear description of what the problem is
      placeholder: "I'm always frustrated when..."

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Any alternative solutions or features you've considered

  - type: dropdown
    id: component
    attributes:
      label: Which component does this affect?
      options:
        - Traefik Proxy
        - Monitoring Stack (Grafana/Prometheus)
        - n8n Automation
        - Systemd Services
        - Makefile/Deployment
        - Documentation
        - CI/CD
        - General Infrastructure

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Low (configuration change, documentation)
        - Medium (new service, integration)
        - High (major architecture change)
        - Unknown

  - type: textarea
    id: implementation
    attributes:
      label: Implementation ideas
      description: If you have ideas on how to implement this, please share
      placeholder: |
        - Add new Docker service
        - Modify existing configuration
        - Update documentation
        - etc.

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples about the feature request
