#!/bin/sh
# Bootstrap qBittorrent: set WebUI credentials.
# Auth bypass (subnet whitelist + reverse proxy) is pre-configured via the
# config template rendered by qbittorrent-pre-start.sh, so setPreferences
# can be called unauthenticated from 127.0.0.1.
# A post-start hook (scripts/stack-up.sh), so it runs after docker compose up. Idempotent.

set -eu

. "$(dirname "$0")/lib.sh"

MAX_RETRIES=60
RETRY_INTERVAL=5
QB_CONTAINER="${QB_CONTAINER:-pi-qbittorrent}"
QB_API="http://127.0.0.1:8080/api/v2"
# ntfy: on-completion notification. qBittorrent shares gluetun's netns (attached to
# frontend), so it reaches ntfy at http://ntfy. Uses a scoped token (rw on 'downloads')
# generated by ntfy-pre-start.sh so the raw password never lands in qBittorrent.conf.
NTFY_ENV_FILE="$PROJECT_DIR/config/ntfy/ntfy.env"
NTFY_COMPLETE_URL="http://ntfy/downloads"
# The qBittorrent category Prowlarr routes Books releases into. Its save path is the
# folder compose mounts into Kavita as /library:ro, so it must stay in step with the
# kavita volume in compose.yaml and with scripts/kavita-pre-start.sh.
BOOKS_CATEGORY="books"
BOOKS_SAVE_PATH="/downloads/books"

qb_curl() {
    docker exec "$QB_CONTAINER" curl -sS "$@"
}

wait_for_qbittorrent() {
    log "Waiting for qBittorrent WebUI to be ready..."
    if wait_for_cmd "$MAX_RETRIES" "$RETRY_INTERVAL" qb_curl -f "$QB_API/app/webapiVersion"; then
        log "qBittorrent WebUI is ready"
        return 0
    fi
    log "ERROR: qBittorrent WebUI did not become ready in time"
    return 1
}

# Returns 0 when expected credentials are persisted in qBittorrent.conf.
# We intentionally avoid auth/login checks here because localhost bypass can
# make login checks return false positives.
credentials_configured() {
    local username="$1"
    local conf
    conf=$(docker exec "$QB_CONTAINER" cat /config/qBittorrent/qBittorrent.conf 2>/dev/null) || return 1
    printf '%s\n' "$conf" | grep -Fq "WebUI\\Username=$username" || return 1
    printf '%s\n' "$conf" | grep -Fq 'WebUI\Password_PBKDF2=' || return 1
    return 0
}

# Unauthenticated: the config template enables auth bypass for 127.0.0.1.
set_credentials() {
    local username="$1"
    local password="$2"
    local prefs="" http_code=""
    # jq renders the JSON and --data-urlencode encodes the form field, as in
    # configure_autorun below. Sending the body raw would let qBittorrent's
    # form parser decode a '+' in the password back to a space (silently
    # storing a login nobody can use), and a '"' or '&' would corrupt the body.
    # The password goes through the environment, not argv, to keep it off the
    # host's process table.
    prefs="$(QB_WEB_UI_PASSWORD="$password" jq -nc --arg u "$username" \
        '{web_ui_username: $u, web_ui_password: $ENV.QB_WEB_UI_PASSWORD}')"
    http_code="$(printf '%s' "$prefs" | docker exec -i "$QB_CONTAINER" curl -sS \
        -H "Referer: http://127.0.0.1:8080" \
        -w "%{http_code}" \
        -o /dev/null \
        --data-urlencode "json@-" \
        "$QB_API/app/setPreferences")"
    # Non-fatal: the notifications below must still get configured, and the WebUI
    # stays reachable behind the VPN + Authelia either way.
    if [ "$http_code" != "200" ]; then
        log "WARNING: credentials setPreferences returned HTTP $http_code (WebUI login left unchanged)"
        return 1
    fi
    log "Credentials set"
}

# Configure the "run external program on torrent completion" hook to POST the finished
# torrent name to ntfy. qBittorrent tokenises the command itself and substitutes %N as a
# single argument (spaces-safe), running curl directly — no shell, no quoting hazard.
# Idempotent: only writes when the stored program differs. Best-effort (warns, no die).
configure_autorun() {
    local token program current prefs http_code
    token="$(read_env_value_from_file "$NTFY_ENV_FILE" NTFY_QBITTORRENT_TOKEN)"
    [ -n "$token" ] || { log "WARNING: NTFY_QBITTORRENT_TOKEN not found in $NTFY_ENV_FILE; skipping autorun"; return 0; }

    program="/usr/bin/curl -sS -H \"Authorization: Bearer ${token}\" -H \"Title: Torrent complete\" -H \"Tags: white_check_mark\" -d %N ${NTFY_COMPLETE_URL}"

    current="$(qb_curl "$QB_API/app/preferences" 2>/dev/null | jq -r '.autorun_program // ""' 2>/dev/null || true)"
    if [ "$current" = "$program" ]; then
        log "qBittorrent autorun (ntfy) already configured, skipping"
        return 0
    fi

    prefs="$(jq -nc --arg p "$program" '{autorun_enabled: true, autorun_program: $p}')"
    http_code="$(printf '%s' "$prefs" | docker exec -i "$QB_CONTAINER" curl -sS -o /dev/null -w '%{http_code}' \
        -H "Referer: http://127.0.0.1:8080" \
        --data-urlencode "json@-" \
        "$QB_API/app/setPreferences")"
    if [ "$http_code" = "200" ]; then
        log "Configured qBittorrent on-completion ntfy notification"
    else
        log "WARNING: qBittorrent autorun setPreferences returned HTTP $http_code"
    fi
}

# Create the "books" category, whose save path is the only download subfolder Kavita
# reads (compose mounts it as /library:ro). Prowlarr maps every newznab Books release
# to this category (scripts/prowlarr-bootstrap.sh), so book grabs land in a folder
# Kavita scans while software grabs stay in the download root, out of its sight.
# Without it Kavita would either see the whole root (installer trees become series) or
# an empty folder. Idempotent: creates when missing, corrects a drifted save path.
# Best-effort (warns, no die).
ensure_books_category() {
    local categories exists current http_code endpoint
    categories="$(qb_curl "$QB_API/torrents/categories" 2>/dev/null || true)"
    # Existence and save path are two separate questions: a category created through
    # the WebUI without an explicit path reports savePath "" (AutoTMM then derives
    # /downloads/<name>), and an empty path must not be read as "not there yet" -
    # createCategory rejects a name that already exists.
    exists="$(printf '%s' "$categories" \
        | jq -r --arg c "$BOOKS_CATEGORY" 'if has($c) then "yes" else "" end' 2>/dev/null || true)"
    current="$(printf '%s' "$categories" \
        | jq -r --arg c "$BOOKS_CATEGORY" '.[$c].savePath // ""' 2>/dev/null || true)"

    if [ "$current" = "$BOOKS_SAVE_PATH" ]; then
        log "qBittorrent '$BOOKS_CATEGORY' category already configured, skipping"
        return 0
    fi

    # createCategory errors on an existing name, editCategory on a missing one.
    if [ "$exists" = "yes" ]; then
        endpoint="editCategory"
    else
        endpoint="createCategory"
    fi

    http_code="$(docker exec "$QB_CONTAINER" curl -sS -o /dev/null -w '%{http_code}' \
        -H "Referer: http://127.0.0.1:8080" \
        --data-urlencode "category=$BOOKS_CATEGORY" \
        --data-urlencode "savePath=$BOOKS_SAVE_PATH" \
        "$QB_API/torrents/$endpoint")"
    if [ "$http_code" = "200" ]; then
        log "Set qBittorrent '$BOOKS_CATEGORY' category save path to $BOOKS_SAVE_PATH"
    else
        log "WARNING: qBittorrent torrents/$endpoint returned HTTP $http_code"
    fi
}

main() {
    wait_for_qbittorrent

    local username password
    username="$(get_env_value ADMIN_USER)"
    password="$(get_env_value PASSWORD)"
    [ -n "$username" ] && [ -n "$password" ] || die "ADMIN_USER or PASSWORD not set in .env"

    # Best-effort: a failure here must not stop the notification setup below.
    if credentials_configured "$username"; then
        log "Credentials already configured, skipping"
    elif [ "${#username}" -lt 3 ]; then
        # qBittorrent 5.x rejects usernames < 3 chars; don't retry every boot.
        log "ADMIN_USER '$username' is under qBittorrent's 3-char minimum; leaving WebUI on its default login"
    else
        log "Setting credentials..."
        set_credentials "$username" "$password" || true
    fi

    configure_autorun
    ensure_books_category
    log "qBittorrent bootstrap complete"
}

main
