#!/bin/sh
# Bootstrap qBittorrent: set WebUI credentials.
# Auth bypass (subnet whitelist + reverse proxy) is pre-configured via the
# config template rendered by qbittorrent-pre-start.sh, so setPreferences
# can be called unauthenticated from 127.0.0.1.
# A post-start hook (scripts/stack-up.sh), so it runs after docker compose up. Idempotent.

set -eu

. "$(dirname "$0")/lib.sh"

MAX_RETRIES=60
RETRY_INTERVAL=5
QB_CONTAINER="${QB_CONTAINER:-pi-qbittorrent}"
QB_API="http://127.0.0.1:8080/api/v2"
# ntfy: on-completion notification. qBittorrent shares gluetun's netns (attached to
# frontend), so it reaches ntfy at http://ntfy. Uses a scoped token (rw on 'downloads')
# generated by ntfy-pre-start.sh so the raw password never lands in qBittorrent.conf.
NTFY_ENV_FILE="$PROJECT_DIR/config/ntfy/ntfy.env"
NTFY_COMPLETE_URL="http://ntfy/downloads"
# The categories that route a release to a library, "<name>:<save path>". Each save
# path is a folder compose mounts into a reader, so this list must stay in step with
# the kavita and audiobookshelf volumes in compose.yaml, with scripts/kavita-pre-start.sh
# and with scripts/audiobookshelf-pre-start.sh. Prowlarr maps its grabs onto the first
# three (scripts/prowlarr-bootstrap.sh); they double as the categories to pick by hand
# when adding a torrent, which is the only way a manual add reaches a library at all -
# an uncategorised torrent lands in the download root, which nothing indexes.
#
#   books       -> Kavita's Book library
#   manga       -> Kavita's Manga library
#   audiobooks  -> Audiobookshelf
#
# Comics deliberately has no category: Kapowarr owns comics/ and moves files inside it
# with copy-then-delete, so a torrent seeding from that tree races its renames.
#
# shelfmark-audiobooks is staging, not a library: it shares /downloads/shelfmark with
# the plain shelfmark category so a raw release tree never reaches a reader, and exists
# only so qBittorrent's list shows which staged grab is an audiobook (compose.yaml's
# QBITTORRENT_CATEGORY_AUDIOBOOK). Its save path has to be set explicitly - left empty,
# AutoTMM would derive /downloads/shelfmark-audiobooks from the name and split the tree.
# The plain shelfmark category is deliberately absent: its empty save path already
# resolves to the same folder through AutoTMM, and rewriting it would ask qBittorrent to
# relocate torrents that are seeding.
#
# Everything else keeps the client default ("prowlarr"), which no reader looks at.
LIBRARY_CATEGORIES="manga:/downloads/manga books:/downloads/books audiobooks:/downloads/audiobooks shelfmark-audiobooks:/downloads/shelfmark"

qb_curl() {
    docker exec "$QB_CONTAINER" curl -sS "$@"
}

wait_for_qbittorrent() {
    log "Waiting for qBittorrent WebUI to be ready..."
    if wait_for_cmd "$MAX_RETRIES" "$RETRY_INTERVAL" qb_curl -f "$QB_API/app/webapiVersion"; then
        log "qBittorrent WebUI is ready"
        return 0
    fi
    log "ERROR: qBittorrent WebUI did not become ready in time"
    return 1
}

# Returns 0 when expected credentials are persisted in qBittorrent.conf.
# We intentionally avoid auth/login checks here because localhost bypass can
# make login checks return false positives.
credentials_configured() {
    local username="$1"
    local conf
    conf=$(docker exec "$QB_CONTAINER" cat /config/qBittorrent/qBittorrent.conf 2>/dev/null) || return 1
    printf '%s\n' "$conf" | grep -Fq "WebUI\\Username=$username" || return 1
    printf '%s\n' "$conf" | grep -Fq 'WebUI\Password_PBKDF2=' || return 1
    return 0
}

# lib.sh's qbittorrent_set_credentials is the shared call; rotate-password.sh
# makes the same one after a leak.
set_credentials() {
    local username="$1"
    local password="$2"
    local http_code=""

    http_code="$(qbittorrent_set_credentials "$QB_CONTAINER" "$username" "$password")"
    # Non-fatal: the notifications below must still get configured, and the WebUI
    # stays reachable behind the VPN + Authelia either way.
    if [ "$http_code" != "200" ]; then
        log "WARNING: credentials setPreferences returned HTTP $http_code (WebUI login left unchanged)"
        return 1
    fi
    log "Credentials set"
}

# Configure the "run external program on torrent completion" hook to POST the finished
# torrent name to ntfy. qBittorrent tokenises the command itself and substitutes %N as a
# single argument (spaces-safe), running curl directly — no shell, no quoting hazard.
# Idempotent: only writes when the stored program differs. Best-effort (warns, no die).
configure_autorun() {
    local token program current prefs http_code
    token="$(read_env_value_from_file "$NTFY_ENV_FILE" NTFY_QBITTORRENT_TOKEN)"
    [ -n "$token" ] || { log "WARNING: NTFY_QBITTORRENT_TOKEN not found in $NTFY_ENV_FILE; skipping autorun"; return 0; }

    program="/usr/bin/curl -sS -H \"Authorization: Bearer ${token}\" -H \"Title: Torrent complete\" -H \"Tags: white_check_mark\" -d %N ${NTFY_COMPLETE_URL}"

    current="$(qb_curl "$QB_API/app/preferences" 2>/dev/null | jq -r '.autorun_program // ""' 2>/dev/null || true)"
    if [ "$current" = "$program" ]; then
        log "qBittorrent autorun (ntfy) already configured, skipping"
        return 0
    fi

    prefs="$(jq -nc --arg p "$program" '{autorun_enabled: true, autorun_program: $p}')"
    http_code="$(printf '%s' "$prefs" | docker exec -i "$QB_CONTAINER" curl -sS -o /dev/null -w '%{http_code}' \
        -H "Referer: http://127.0.0.1:8080" \
        --data-urlencode "json@-" \
        "$QB_API/app/setPreferences")"
    if [ "$http_code" = "200" ]; then
        log "Configured qBittorrent on-completion ntfy notification"
    else
        log "WARNING: qBittorrent autorun setPreferences returned HTTP $http_code"
    fi
}

# Create the categories whose save paths Kavita indexes, so a Books or Comics grab
# lands in a folder Kavita scans while everything else stays in the download root and
# out of its sight. Prowlarr maps releases to them (scripts/prowlarr-bootstrap.sh).
# Idempotent: creates when missing, corrects a drifted save path. Best-effort.
ensure_library_categories() {
    local categories entry name path exists current http_code endpoint
    categories="$(qb_curl "$QB_API/torrents/categories" 2>/dev/null || true)"

    # Word splitting on the list is the parse; no entry contains whitespace.
    # shellcheck disable=SC2086
    for entry in $LIBRARY_CATEGORIES; do
        name="${entry%%:*}"
        path="${entry#*:}"

        # A category created in the WebUI reports savePath "" (AutoTMM derives the
        # path), so an empty path is not "missing" - and createCategory rejects an
        # existing name.
        exists="$(printf '%s' "$categories" \
            | jq -r --arg c "$name" 'if has($c) then "yes" else "" end' 2>/dev/null || true)"
        current="$(printf '%s' "$categories" \
            | jq -r --arg c "$name" '.[$c].savePath // ""' 2>/dev/null || true)"

        if [ "$current" = "$path" ]; then
            log "qBittorrent '$name' category already configured, skipping"
            continue
        fi

        # createCategory errors on an existing name, editCategory on a missing one.
        if [ "$exists" = "yes" ]; then
            endpoint="editCategory"
        else
            endpoint="createCategory"
        fi

        http_code="$(docker exec "$QB_CONTAINER" curl -sS -o /dev/null -w '%{http_code}' \
            -H "Referer: http://127.0.0.1:8080" \
            --data-urlencode "category=$name" \
            --data-urlencode "savePath=$path" \
            "$QB_API/torrents/$endpoint")"
        if [ "$http_code" = "200" ]; then
            log "Set qBittorrent '$name' category save path to $path"
        else
            log "WARNING: qBittorrent torrents/$endpoint for '$name' returned HTTP $http_code"
        fi
    done
}

main() {
    wait_for_qbittorrent

    local username password
    username="$(get_env_value ADMIN_USER)"
    password="$(get_env_value PASSWORD)"
    [ -n "$username" ] && [ -n "$password" ] || die "ADMIN_USER or PASSWORD not set in .env"

    # Best-effort: a failure here must not stop the notification setup below.
    if credentials_configured "$username"; then
        log "Credentials already configured, skipping"
    elif [ "${#username}" -lt 3 ]; then
        # qBittorrent 5.x rejects usernames < 3 chars; don't retry every boot.
        log "ADMIN_USER '$username' is under qBittorrent's 3-char minimum; leaving WebUI on its default login"
    else
        log "Setting credentials..."
        set_credentials "$username" "$password" || true
    fi

    configure_autorun
    ensure_library_categories
    log "qBittorrent bootstrap complete"
}

main
