#!/bin/sh
# Bootstrap qBittorrent: set WebUI credentials.
# Auth bypass (subnet whitelist + reverse proxy) is pre-configured via the
# config template rendered by qbittorrent-pre-start.sh, so setPreferences
# can be called unauthenticated from 127.0.0.1.
# Runs as ExecStartPost after docker compose up. Idempotent.

set -e

. "$(dirname "$0")/lib.sh"

MAX_RETRIES=60
RETRY_INTERVAL=5
QB_CONTAINER="${QB_CONTAINER:-pi-qbittorrent}"
QB_API="http://127.0.0.1:8080/api/v2"
# ntfy: on-completion notification. qBittorrent shares gluetun's netns (attached to
# frontend), so it reaches ntfy at http://ntfy. Uses a scoped token (rw on 'downloads')
# generated by ntfy-pre-start.sh so the raw password never lands in qBittorrent.conf.
NTFY_ENV_FILE="$PROJECT_DIR/config/ntfy/ntfy.env"
NTFY_COMPLETE_URL="http://ntfy/downloads"

qb_curl() {
    docker exec "$QB_CONTAINER" curl -sS "$@"
}

wait_for_qbittorrent() {
    log "Waiting for qBittorrent WebUI to be ready..."
    for i in $(seq 1 $MAX_RETRIES); do
        if qb_curl -f "$QB_API/app/webapiVersion" >/dev/null 2>&1; then
            log "qBittorrent WebUI is ready"
            return 0
        fi
        sleep "$RETRY_INTERVAL"
    done
    log "ERROR: qBittorrent WebUI did not become ready in time"
    return 1
}

# Returns 0 when expected credentials are persisted in qBittorrent.conf.
# We intentionally avoid auth/login checks here because localhost bypass can
# make login checks return false positives.
credentials_configured() {
    local username="$1"
    local conf
    conf=$(docker exec "$QB_CONTAINER" cat /config/qBittorrent/qBittorrent.conf 2>/dev/null) || return 1
    printf '%s\n' "$conf" | grep -Fq "WebUI\\Username=$username" || return 1
    printf '%s\n' "$conf" | grep -Fq 'WebUI\Password_PBKDF2=' || return 1
    return 0
}

# Unauthenticated: the config template enables auth bypass for 127.0.0.1.
set_credentials() {
    local username="$1"
    local password="$2"
    local prefs_file http_code
    prefs_file=$(mktemp)
    # shellcheck disable=SC2064
    trap "rm -f $prefs_file" EXIT
    printf 'json={"web_ui_username":"%s","web_ui_password":"%s"}' \
        "$username" "$password" > "$prefs_file"
    http_code=$(docker exec -i "$QB_CONTAINER" curl -sS \
        -X POST \
        -H "Referer: http://127.0.0.1:8080" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        -w "%{http_code}" \
        -o /dev/null \
        --data @- \
        "$QB_API/app/setPreferences" < "$prefs_file")
    rm -f "$prefs_file"
    # Non-fatal: the notifications below must still get configured, and the WebUI
    # stays reachable behind the VPN + Authelia either way.
    if [ "$http_code" != "200" ]; then
        log "WARNING: credentials setPreferences returned HTTP $http_code (WebUI login left unchanged)"
        return 1
    fi
    log "Credentials set"
}

# Configure the "run external program on torrent completion" hook to POST the finished
# torrent name to ntfy. qBittorrent tokenises the command itself and substitutes %N as a
# single argument (spaces-safe), running curl directly — no shell, no quoting hazard.
# Idempotent: only writes when the stored program differs. Best-effort (warns, no die).
configure_autorun() {
    local token program current prefs http_code
    token="$(read_env_value_from_file "$NTFY_ENV_FILE" NTFY_QBITTORRENT_TOKEN)"
    [ -n "$token" ] || { log "WARNING: NTFY_QBITTORRENT_TOKEN not found in $NTFY_ENV_FILE; skipping autorun"; return 0; }

    program="/usr/bin/curl -sS -H \"Authorization: Bearer ${token}\" -H \"Title: Torrent complete\" -H \"Tags: white_check_mark\" -d %N ${NTFY_COMPLETE_URL}"

    current="$(qb_curl "$QB_API/app/preferences" 2>/dev/null | jq -r '.autorun_program // ""' 2>/dev/null || true)"
    if [ "$current" = "$program" ]; then
        log "qBittorrent autorun (ntfy) already configured, skipping"
        return 0
    fi

    prefs="$(jq -nc --arg p "$program" '{autorun_enabled: true, autorun_program: $p}')"
    http_code="$(printf '%s' "$prefs" | docker exec -i "$QB_CONTAINER" curl -sS -o /dev/null -w '%{http_code}' \
        -H "Referer: http://127.0.0.1:8080" \
        --data-urlencode "json@-" \
        "$QB_API/app/setPreferences")"
    if [ "$http_code" = "200" ]; then
        log "Configured qBittorrent on-completion ntfy notification"
    else
        log "WARNING: qBittorrent autorun setPreferences returned HTTP $http_code"
    fi
}

main() {
    wait_for_qbittorrent

    local username password
    username="$(get_env_value ADMIN_USER)"
    password="$(get_env_value PASSWORD)"
    [ -n "$username" ] && [ -n "$password" ] || die "ADMIN_USER or PASSWORD not set in .env"

    # Best-effort: a failure here must not stop the notification setup below.
    if credentials_configured "$username"; then
        log "Credentials already configured, skipping"
    elif [ "${#username}" -lt 3 ]; then
        # qBittorrent 5.x rejects usernames < 3 chars; don't retry every boot.
        log "ADMIN_USER '$username' is under qBittorrent's 3-char minimum; leaving WebUI on its default login"
    else
        log "Setting credentials..."
        set_credentials "$username" "$password" || true
    fi

    configure_autorun
    log "qBittorrent bootstrap complete"
}

main
