#!/bin/bash
set -e

# Create a temporary SQL file with environment variables substituted
TEMP_SQL=$(mktemp)
trap "rm -f $TEMP_SQL" EXIT

cat > "$TEMP_SQL" << EOF
-- Create Immich database and user
DO \$\$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${IMMICH_DB_USER}') THEN
		CREATE USER ${IMMICH_DB_USER} WITH ENCRYPTED PASSWORD '${IMMICH_DB_PASSWORD}';
	ELSE
		ALTER USER ${IMMICH_DB_USER} WITH ENCRYPTED PASSWORD '${IMMICH_DB_PASSWORD}';
	END IF;
END
\$\$;
SELECT 'CREATE DATABASE ${IMMICH_DB_NAME}'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${IMMICH_DB_NAME}')
\gexec
ALTER USER ${IMMICH_DB_USER} WITH SUPERUSER;
GRANT ALL PRIVILEGES ON DATABASE ${IMMICH_DB_NAME} TO ${IMMICH_DB_USER};
ALTER DATABASE ${IMMICH_DB_NAME} OWNER TO ${IMMICH_DB_USER};

-- Create Nextcloud database and user
DO \$\$
BEGIN
	IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${NEXTCLOUD_DB_USER}') THEN
		CREATE USER ${NEXTCLOUD_DB_USER} WITH ENCRYPTED PASSWORD '${NEXTCLOUD_DB_PASSWORD}';
	ELSE
		ALTER USER ${NEXTCLOUD_DB_USER} WITH ENCRYPTED PASSWORD '${NEXTCLOUD_DB_PASSWORD}';
	END IF;
END
\$\$;
SELECT 'CREATE DATABASE ${NEXTCLOUD_DB_NAME}'
WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = '${NEXTCLOUD_DB_NAME}')
\gexec
GRANT ALL PRIVILEGES ON DATABASE ${NEXTCLOUD_DB_NAME} TO ${NEXTCLOUD_DB_USER};
ALTER DATABASE ${NEXTCLOUD_DB_NAME} OWNER TO ${NEXTCLOUD_DB_USER};

-- Set proper permissions for Immich user on Immich DB
\connect ${IMMICH_DB_NAME}
CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
GRANT ALL ON SCHEMA public TO ${IMMICH_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${IMMICH_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${IMMICH_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO ${IMMICH_DB_USER};

-- Set proper permissions for Nextcloud user on Nextcloud DB
\connect ${NEXTCLOUD_DB_NAME}
GRANT ALL ON SCHEMA public TO ${NEXTCLOUD_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${NEXTCLOUD_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${NEXTCLOUD_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO ${NEXTCLOUD_DB_USER};
EOF

# Execute the SQL file
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" < "$TEMP_SQL"
