name: Raspberry Pi Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: "0 2 * * 0"

jobs:
  test-arm64:
    name: Test ARM64 Compatibility
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,arm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create test environment
        run: |
          echo "HOST_NAME=pi.test" > .env
          echo "USER=testuser" >> .env
          echo "EMAIL=test@example.com" >> .env
          echo "PASSWORD=testpass123" >> .env

      - name: Test multi-arch image compatibility
        run: |
          # Test Traefik ARM compatibility
          docker run --platform ${{ matrix.platform }} --rm traefik:v3.4 version

          # Test Grafana ARM compatibility
          docker run --platform ${{ matrix.platform }} --rm grafana/grafana:latest --version

          # Test Prometheus ARM compatibility
          docker run --platform ${{ matrix.platform }} --rm prom/prometheus:latest --version

          # Test n8n ARM compatibility
          docker run --platform ${{ matrix.platform }} --rm n8nio/n8n:latest --version

          # Test Pi Hole ARM compatibility
          docker run --platform ${{ matrix.platform }} --rm pihole/pihole:latest --version

      - name: Build and test on ARM
        run: |
          # Create networks
          docker network create monitoring || true
          docker network create frontend || true
          docker compose build

  install:
    name: Validate install and systemd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install systemd
        run: |
          sudo apt-get update
          sudo apt-get install -y systemd

      - name: Test Makefile install systemd
        run: |
          make install
          test -f /etc/systemd/system/pi-web.service
          sudo systemd-analyze verify /etc/systemd/system/pi-web.service
          test -f /etc/systemd/system/pi-web-restart.service
          sudo systemd-analyze verify /etc/systemd/system/pi-web-restart.service
          test -f /etc/systemd/system/pi-web-restart.timer
          sudo systemd-analyze verify /etc/systemd/system/pi-web-restart.timer

  dependency-check:
    name: Check Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check required tools availability
        run: |
          # Test Docker availability
          docker --version
          docker compose version

          # Test make availability
          make --version

          # Test git availability (for make update)
          git --version
